{% set version = "2.3.2" %}
{% set sha256 = "76940cd4e778e8093579a9d195b25fff5e936e9dc6242068528b437a76764f91" %}

package:
  name: libidn2
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/libidn/libidn2-{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  skip: True  # [win]
  number: 0
  run_exports:
    # _Amazing_ backwards compatibility so pin to major number:
    #    https://abi-laboratory.pro/tracker/timeline/libidn2/
    - {{ pin_subpackage('libidn2', min_pin='x', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - libunistring

test:
  commands:
    - test -f "${PREFIX}/include/idn2.h"
    - test -f "${PREFIX}/lib/libidn2${SHLIB_EXT}"
    - test ! -f "${PREFIX}/lib/libidn2.a"

about:
  home: https://www.gnu.org/software/libidn/#libidn2
  license: LGPLv2 AND LGPL-3.0-or-later AND GPL-3.0-or-later
  license_file: COPYING
  summary: "Library for internationalized domain names (IDNA2008) support"
  dev_url: https://gitlab.com/libidn/libidn2
  doc_url: https://libidn.gitlab.io/libidn2/manual/libidn2.html

extra:
  recipe-maintainers:
    - hmaarrfk
    - chenghlee
